In [20]:
import pandas as pd

# import csv
data = pd.read_csv("/Users/ca/Data /IND_CH_US/PopulationData IND-CH-US.csv")
data

,Series Name,"Population, total","Population, total.1","Population, total.2","Population, male","Population, male.1","Population, male.2","Population, female","Population, female.1","Population, female.2",...,"Suicide mortality rate, male (per 100,000 male population).2",Unemployment with advanced education (% of total labor force with advanced education),Unemployment with advanced education (% of total labor force with advanced education).1,Unemployment with advanced education (% of total labor force with advanced education).2,"Unemployment with advanced education, female (% of female labor force with advanced education)","Unemployment with advanced education, female (% of female labor force with advanced education).1","Unemployment with advanced education, female (% of female labor force with advanced education).2","Unemployment with advanced education, male (% of male labor force with advanced education)","Unemployment with advanced education, male (% of male labor force with advanced education).1","Unemployment with advanced education, male (% of male labor force with advanced education).2"
0,Country Name,India,China,United States,India,China,United States,India,China,United States,...,United States,India,China,United States,India,China,United States,India,China,United States
1,2000,1059633675,1262645000,282162411,548223581,645562937,138910694,511410095,617082063,143251716,...,17.7,10.31,..,1.93,21.12,..,2.09,8.39,..,1.79
2,2001,1078970907,1271850000,284968955,558291332,650413443,140343133,520679574,621436557,144625822,...,18.3,..,..,2.56,..,..,2.59,..,..,2.54
3,2002,1098313039,1280400000,287625193,568334873,654865007,141652391,529978166,625534993,145972802,...,18.8,..,..,3.33,..,..,3.17,..,..,3.47
4,2003,1117415123,1288400000,290107933,578236241,659030348,142865707,539178882,629369651,147242226,...,18.6,..,..,3.46,..,..,3.25,..,..,3.65
5,2004,1136264583,1296075000,292805298,587990365,663027988,144210567,548274218,633047012,148594732,...,18.6,..,..,3.1,..,..,3.06,..,..,3.14
6,2005,1154638713,1303720000,295516599,597477666,667008138,145570277,557161047,636711861,149946323,...,18.7,10.2,..,2.71,21.4,..,2.79,7.72,..,2.63
7,2006,1172373788,1311020000,298379912,606611392,670816557,146996229,565762395,640203444,151383683,...,19.1,..,..,2.43,..,..,2.52,..,..,2.34
8,2007,1189691809,1317885000,301231207,615506279,674398683,148402076,574185530,643486317,152829130,...,19.5,..,..,2.42,..,..,2.5,..,..,2.34
9,2008,1206734806,1324655000,304093966,624242020,677925783,149804127,582492785,646729218,154289840,...,20,..,..,3.01,..,..,3.1,..,..,2.93
10,2009,1223640160,1331260000,306771529,632892402,681368810,151111335,590747758,649891191,155660194,...,20,..,..,5.34,..,..,5.03,..,..,5.65
11,2010,1240613620,1337705000,309327143,641566029,684712330,152358841,599047591,652992671,156968302,...,20.5,7.5,..,5.47,16.04,..,5.26,5.6,..,5.69
12,2011,1257621191,1345035000,311583481,650244390,688484213,153539494,607376801,656550787,158043988,...,20.9,..,..,5.14,..,..,5.17,..,..,5.1
13,2012,1274487215,1354190000,313877662,658839435,693176026,154813215,615647779,661013974,159064447,...,21.1,8.09,..,4.74,15.3,..,4.99,6.37,..,4.49
14,2013,1291132063,1363240000,316059947,667322883,697792609,156025758,623809180,665447390,160034189,...,21,..,..,4.32,..,..,4.45,..,..,4.19
15,2014,1307246509,1371860000,318386329,675549357,702159650,157301571,631697152,669700351,161084758,...,21.6,..,..,3.69,..,..,3.82,..,..,3.56
16,2015,1322866505,1379860000,320738994,683543213,706169297,158580581,639323292,673690703,162158414,...,22.2,..,..,3.03,..,..,3.15,..,..,2.91
17,2016,1338636340,1387790000,323071755,691623419,710100087,159847727,647012921,677689913,163224028,...,23.5,..,..,2.91,..,..,2.96,..,..,2.86
18,2017,1354195680,1396215000,325122128,699587889,714208198,160970309,654607791,682006802,164151818,...,24.9,..,..,2.69,..,..,2.79,..,..,2.58
19,2018,1369003306,1402760000,326838199,707149230,717291023,161911851,661854076,685468978,164926348,...,24.3,16.51,..,2.45,25.44,..,2.48,14.04,..,2.42
20,2019,1383112050,1407745000,328329953,714325057,719565010,162730147,668786993,688179990,165599805,...,25,15.73,..,2.38,22.58,..,2.41,13.56,..,2.35
21,2020,1396387127,1411100000,331511512,720997448,720928153,164308503,675389679,690171848,167203010,...,..,17.91,..,5.59,26.78,..,5.96,15.27,..,5.2
22,2021,1407563842,1412360000,332031554,726503429,721140373,164481553,681060412,691219627,167550001,...,..,15.78,..,3.58,23.39,..,3.58,13.5,..,3.57
23,2022,1417173173,1412175000,333287557,731180498,720646499,165021339,685992675,691528501,168266219,...,..,14.3,..,2.32,21.43,..,2.32,12.05,..,2.33

In [27]:
data.columns = data.columns.str.replace(',', ' ').str.replace('', '')
# Display the structure of the data
# print(data.info())
print(data.describe())
# data.columns

         Series Name Population  total Population  total.1  \
count             24                24                  24
unique            24                24                  24
top     Country Name             India               China
freq               1                 1                   1

       Population  total.2 Population  male Population  male.1  \
count                   24               24                 24
unique                  24               24                 24
top          United States            India              China
freq                     1                1                  1

       Population  male.2 Population  female Population  female.1  \
count                  24                 24                   24
unique                 24                 24                   24
top         United States              India                China
freq                    1                  1                    1

       Population  female.2  ...  \
count                    24  ...
unique                   24  ...
top           United States  ...
freq                      1  ...

       Suicide mortality rate  male (per 100 000 male population).2  \
count                                                  24
unique                                                 20
top                                                    ..
freq                                                    3

       Unemployment with advanced education (% of total labor force with advanced education)  \
count                                                  24
unique                                                 11
top                                                    ..
freq                                                   14

       Unemployment with advanced education (% of total labor force with advanced education).1  \
count                                                  24
unique                                                  2
top                                                    ..
freq                                                   23

       Unemployment with advanced education (% of total labor force with advanced education).2  \
count                                                  24
unique                                                 24
top                                         United States
freq                                                    1

       Unemployment with advanced education  female (% of female labor force with advanced education)  \
count                                                  24
unique                                                 11
top                                                    ..
freq                                                   14

       Unemployment with advanced education  female (% of female labor force with advanced education).1  \
count                                                  24
unique                                                  2
top                                                    ..
freq                                                   23

       Unemployment with advanced education  female (% of female labor force with advanced education).2  \
count                                                  24
unique                                                 23
top                                                  2.79
freq                                                    2

       Unemployment with advanced education  male (% of male labor force with advanced education)  \
count                                                  24
unique                                                 11
top                                                    ..
freq                                                   14

       Unemployment with advanced education  male (% of male labor force with advanced education).1  \
count                                                  24
unique                                                  2
top                                                    ..
freq                                                   23

       Unemployment with advanced education  male (% of male labor force with advanced education).2
count                                                  24
unique                                                 23
top                                                  2.34
freq                                                    2

[4 rows x 25 columns]

In [25]:
data

,Series Name,Population total,Population total.1,Population total.2,Population male,Population male.1,Population male.2,Population female,Population female.1,Population female.2,...,Suicide mortality rate male (per 100 000 male population).2,Unemployment with advanced education (% of total labor force with advanced education),Unemployment with advanced education (% of total labor force with advanced education).1,Unemployment with advanced education (% of total labor force with advanced education).2,Unemployment with advanced education female (% of female labor force with advanced education),Unemployment with advanced education female (% of female labor force with advanced education).1,Unemployment with advanced education female (% of female labor force with advanced education).2,Unemployment with advanced education male (% of male labor force with advanced education),Unemployment with advanced education male (% of male labor force with advanced education).1,Unemployment with advanced education male (% of male labor force with advanced education).2
0,Country Name,India,China,United States,India,China,United States,India,China,United States,...,United States,India,China,United States,India,China,United States,India,China,United States
1,2000,1059633675,1262645000,282162411,548223581,645562937,138910694,511410095,617082063,143251716,...,17.7,10.31,..,1.93,21.12,..,2.09,8.39,..,1.79
2,2001,1078970907,1271850000,284968955,558291332,650413443,140343133,520679574,621436557,144625822,...,18.3,..,..,2.56,..,..,2.59,..,..,2.54
3,2002,1098313039,1280400000,287625193,568334873,654865007,141652391,529978166,625534993,145972802,...,18.8,..,..,3.33,..,..,3.17,..,..,3.47
4,2003,1117415123,1288400000,290107933,578236241,659030348,142865707,539178882,629369651,147242226,...,18.6,..,..,3.46,..,..,3.25,..,..,3.65
5,2004,1136264583,1296075000,292805298,587990365,663027988,144210567,548274218,633047012,148594732,...,18.6,..,..,3.1,..,..,3.06,..,..,3.14
6,2005,1154638713,1303720000,295516599,597477666,667008138,145570277,557161047,636711861,149946323,...,18.7,10.2,..,2.71,21.4,..,2.79,7.72,..,2.63
7,2006,1172373788,1311020000,298379912,606611392,670816557,146996229,565762395,640203444,151383683,...,19.1,..,..,2.43,..,..,2.52,..,..,2.34
8,2007,1189691809,1317885000,301231207,615506279,674398683,148402076,574185530,643486317,152829130,...,19.5,..,..,2.42,..,..,2.5,..,..,2.34
9,2008,1206734806,1324655000,304093966,624242020,677925783,149804127,582492785,646729218,154289840,...,20,..,..,3.01,..,..,3.1,..,..,2.93
10,2009,1223640160,1331260000,306771529,632892402,681368810,151111335,590747758,649891191,155660194,...,20,..,..,5.34,..,..,5.03,..,..,5.65
11,2010,1240613620,1337705000,309327143,641566029,684712330,152358841,599047591,652992671,156968302,...,20.5,7.5,..,5.47,16.04,..,5.26,5.6,..,5.69
12,2011,1257621191,1345035000,311583481,650244390,688484213,153539494,607376801,656550787,158043988,...,20.9,..,..,5.14,..,..,5.17,..,..,5.1
13,2012,1274487215,1354190000,313877662,658839435,693176026,154813215,615647779,661013974,159064447,...,21.1,8.09,..,4.74,15.3,..,4.99,6.37,..,4.49
14,2013,1291132063,1363240000,316059947,667322883,697792609,156025758,623809180,665447390,160034189,...,21,..,..,4.32,..,..,4.45,..,..,4.19
15,2014,1307246509,1371860000,318386329,675549357,702159650,157301571,631697152,669700351,161084758,...,21.6,..,..,3.69,..,..,3.82,..,..,3.56
16,2015,1322866505,1379860000,320738994,683543213,706169297,158580581,639323292,673690703,162158414,...,22.2,..,..,3.03,..,..,3.15,..,..,2.91
17,2016,1338636340,1387790000,323071755,691623419,710100087,159847727,647012921,677689913,163224028,...,23.5,..,..,2.91,..,..,2.96,..,..,2.86
18,2017,1354195680,1396215000,325122128,699587889,714208198,160970309,654607791,682006802,164151818,...,24.9,..,..,2.69,..,..,2.79,..,..,2.58
19,2018,1369003306,1402760000,326838199,707149230,717291023,161911851,661854076,685468978,164926348,...,24.3,16.51,..,2.45,25.44,..,2.48,14.04,..,2.42
20,2019,1383112050,1407745000,328329953,714325057,719565010,162730147,668786993,688179990,165599805,...,25,15.73,..,2.38,22.58,..,2.41,13.56,..,2.35
21,2020,1396387127,1411100000,331511512,720997448,720928153,164308503,675389679,690171848,167203010,...,..,17.91,..,5.59,26.78,..,5.96,15.27,..,5.2
22,2021,1407563842,1412360000,332031554,726503429,721140373,164481553,681060412,691219627,167550001,...,..,15.78,..,3.58,23.39,..,3.58,13.5,..,3.57
23,2022,1417173173,1412175000,333287557,731180498,720646499,165021339,685992675,691528501,168266219,...,..,14.3,..,2.32,21.43,..,2.32,12.05,..,2.33

In [24]:
# Separating the data for China
df_ch = data.iloc[:, [0] + [col for col in data.columns if col.endswith('1')]]
df_ch

IndexError: .iloc requires numeric indexers, got ['0' 'Population  total.1' 'Population  male.1' 'Population  female.1'
 'Suicide mortality rate  female (per 100 000 female population).1'
 'Suicide mortality rate  male (per 100 000 male population).1'
 'Unemployment with advanced education (% of total labor force with advanced education).1'
 'Unemployment with advanced education  female (% of female labor force with advanced education).1'
 'Unemployment with advanced education  male (% of male labor force with advanced education).1']

In [ ]:
# Remove the second row (index 1)
df_ch = df_ch.drop(1)

# Reset the index to maintain continuous row numbering
df_ch = df_ch.reset_index(drop=True)

# Print the modified DataFrame
print(df_ch)